export const COLOR_SYSTEM = {
  cream: "#FBF7F0",
  warmWhite: "#FFFDF9",
  sand: "#F5EDE0",
  sandLight: "#FAF5EC",
  saffron: "#E8913A",
  saffronLight: "#FFF3E6",
  saffronDark: "#C97A2E",
  turmeric: "#D4A843",
  charcoal: "#1A1A1A",
  charcoalSoft: "#2D2D2D",
  textPrimary: "#1A1A1A",
  textSecondary: "#5C5C5C",
  textMuted: "#8A8A8A",
  border: "#E8E0D4",
  borderLight: "#F0EAE0",
  green: "#2D8C5A",
  greenLight: "#E8F5EE",
  white: "#FFFFFF",
} as const;
