export const doctors = [
  {
    id: "dr-anand-sharma",
    name: "Dr. Anand Sharma",
    photo: "/images/doctors/doctor-2.jpg",
    credentials: "MBBS, MD (Internal Medicine)",
    hospital: "Apollo Hospital, Delhi",
    affiliation: "Apollo Hospitals",
    specialization: "Internal Medicine & Obesity",
    experience: 15,
    rating: 4.9,
    reviews: 230,
    patients: 1850,
    quote: "I believe in treating the root cause, not just symptoms. Every patient's metabolism is unique — cookie-cutter plans don't work.",
    tags: ["Internal Medicine", "Metabolic Health", "Obesity Management"],
    languages: ["English", "Hindi"],
    nextAvailable: "Tomorrow, 10:00 AM",
    bio: "Dr. Anand Sharma is a board-certified internist with over 15 years of experience in metabolic health and obesity management. After training at AIIMS Delhi, he spent 8 years at Apollo Hospital treating patients with complex metabolic conditions. He pioneered the use of GLP-1 therapies for weight management in India and has helped over 1,800 patients achieve sustainable weight loss. His approach combines evidence-based medication with personalized lifestyle modifications.",
    education: [
      "MBBS — All India Institute of Medical Sciences (AIIMS), Delhi",
      "MD (Internal Medicine) — AIIMS, Delhi",
      "Fellowship in Metabolic Medicine — Royal College of Physicians, London",
    ],
    specializations: [
      "GLP-1 receptor agonist therapy",
      "Metabolic syndrome management",
      "Type 2 diabetes reversal",
      "Obesity-related cardiovascular risk",
      "Hormonal imbalance & weight gain",
    ],
  },
  {
    id: "dr-priya-nair",
    name: "Dr. Priya Nair",
    photo: "/images/doctors/doctor-3.jpg",
    credentials: "MBBS, MD (Endocrinology)",
    hospital: "Manipal Hospital, Bangalore",
    affiliation: "AIIMS Delhi",
    specialization: "Endocrinology & Metabolism",
    experience: 12,
    rating: 4.8,
    reviews: 185,
    patients: 1420,
    quote: "Every patient deserves a personalized treatment plan. What works for one body may not work for another — that's why I listen first.",
    tags: ["Endocrinology", "PCOS", "Thyroid", "Insulin Resistance"],
    languages: ["English", "Hindi", "Malayalam", "Kannada"],
    nextAvailable: "Today, 4:30 PM",
    bio: "Dr. Priya Nair is an endocrinologist specializing in hormonal disorders that affect weight — particularly PCOS, thyroid dysfunction, and insulin resistance. After her MD from CMC Vellore, she completed advanced training in reproductive endocrinology. She's passionate about helping women who've been told 'weight loss is impossible' due to hormonal conditions. Her evidence-based protocols have helped over 1,400 patients, with a particular focus on PCOS-related weight management.",
    education: [
      "MBBS — Christian Medical College (CMC), Vellore",
      "MD (Endocrinology) — CMC, Vellore",
      "Advanced Training in Reproductive Endocrinology — KEM Hospital, Mumbai",
    ],
    specializations: [
      "PCOS & weight management",
      "Thyroid disorders",
      "Insulin resistance treatment",
      "Hormonal weight gain in women",
      "Metabolic health in young adults",
    ],
  },
  {
    id: "dr-meenakshi-iyer",
    name: "Dr. Meenakshi Iyer",
    photo: "/images/doctors/doctor-1.jpg",
    credentials: "MBBS, DNB (Medicine)",
    hospital: "Kokilaben Hospital, Mumbai",
    affiliation: "Fortis Healthcare",
    specialization: "Clinical Nutrition & GLP-1 Therapy",
    experience: 18,
    rating: 4.9,
    reviews: 310,
    patients: 2200,
    quote: "Evidence-based medicine combined with compassionate care. I treat my patients the way I'd want my own family to be treated.",
    tags: ["General Medicine", "GLP-1 Therapy", "Diabetes", "Preventive Health"],
    languages: ["English", "Hindi", "Marathi", "Tamil"],
    nextAvailable: "Tomorrow, 11:00 AM",
    bio: "Dr. Meenakshi Iyer brings 18 years of clinical experience in internal medicine with a deep focus on lifestyle diseases and preventive health. Trained at Grant Medical College Mumbai and Kokilaben Hospital, she's one of India's most experienced practitioners of GLP-1 therapy for obesity management. With over 2,200 patients treated, she's known for her thorough, compassionate approach. She believes that sustainable weight loss requires addressing the whole person — not just the number on the scale.",
    education: [
      "MBBS — Grant Medical College, Mumbai",
      "DNB (Medicine) — National Board of Examinations",
      "Certificate in Diabetes Management — International Diabetes Federation",
    ],
    specializations: [
      "GLP-1 therapy & obesity medicine",
      "Type 2 diabetes management",
      "Preventive cardiology",
      "Lifestyle disease reversal",
      "Senior patient metabolic care",
    ],
  },
];
